# base image
FROM python:3.6.6-slim

# install dependencies
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
# RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint-stage.sh
RUN chmod +x /usr/src/app/entrypoint-stage.sh

# add app
COPY . /usr/src/app

# run server
CMD ["sh", "/usr/src/app/entrypoint-stage.sh"]