# base image
FROM node:10.10.0-alpine
# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

#install and cache app dependencies
COPY package.json /usr/src/app/package.json
# COPY . /usr/src/app
RUN npm install --silent
RUN npm install react-scripts@1.1.5 -g --silent
#RUN yarn install --silent
#RUN yarn global add react-scripts@1.1.5 --silent

# start app
CMD ["npm", "start"]